services:
  - type: web
    name: truestate-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn truestate_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: truestate-db
          property: connectionString
